Name: Localiday
Description: localiday.com is the search engine for your local favorite holiday displays
DBVersion: 1
Version: 1.0.0
Author: Rafael Pacheco Chargel
Copyright: Â© 2012 Localiday. All rights reserved.
